[package]
name = "t420babe"
version = "0.0.0"
authors = ["t420babe <t420babe@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2.68"
web-sys = { version = "0.3.45", features = ['console'] }
